# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "roip_token_auth"
  s.version = "0.2.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Watson"]
  s.date = "2011-10-27"
  s.description = "The Upwave, Inc. Rights over IP Access Token authentication for Protected Resources"
  s.email = "david@upwave.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "lib/engine.rb",
    "lib/roip_text_access_token.rb",
    "lib/roip_token_auth.rb"
  ]
  s.homepage = "http://github.com/daviduw/roip_token_auth"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Upwave, Inc. RoIP Token Authentication"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 0"])
      s.add_runtime_dependency(%q<addressable>, [">= 0"])
      s.add_runtime_dependency(%q<lorax>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<addressable>, [">= 0"])
      s.add_dependency(%q<lorax>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<addressable>, [">= 0"])
    s.add_dependency(%q<lorax>, [">= 0"])
  end
end

